name: Publish Library

on:
    push:
        branches:
            - main
        paths:
            - 'packages/**'

jobs:
    build-and-publish:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - uses: actions/checkout@v5

            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '24'
                  registry-url: 'https://npm.pkg.github.com'
                  scope: '@RaffaeleCanale'

            - name: Install pnpm
              run: npm install -g pnpm

            - name: Install dependencies
              run: pnpm install

            - name: Build
              run: pnpm build

            - name: Publish
              run: pnpm publish -r --no-git-checks
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
